<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace Algolia\AlgoliaSearch\Model\AgentStudio;

use Algolia\AlgoliaSearch\Model\AbstractModel;
use Algolia\AlgoliaSearch\Model\ModelInterface;

/**
 * MessagePartAssistantMessageAGUI Class Doc Comment.
 *
 * @category Class
 */
class MessagePartAssistantMessageAGUI extends AbstractModel implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $modelTypes = [
        'type' => 'string',
        'content' => 'string',
        'stepId' => 'string',
        'id' => 'string',
        'name' => 'string',
        'arguments' => 'string',
        'state' => 'string',
        'output' => 'array<string,mixed>',
        'approval' => '\Algolia\AlgoliaSearch\Model\AgentStudio\ToolApprovalAGUI',
        'toolCallId' => 'string',
        'error' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $modelFormats = [
        'type' => null,
        'content' => null,
        'stepId' => null,
        'id' => null,
        'name' => null,
        'arguments' => null,
        'state' => null,
        'output' => null,
        'approval' => null,
        'toolCallId' => null,
        'error' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'content' => 'content',
        'stepId' => 'stepId',
        'id' => 'id',
        'name' => 'name',
        'arguments' => 'arguments',
        'state' => 'state',
        'output' => 'output',
        'approval' => 'approval',
        'toolCallId' => 'toolCallId',
        'error' => 'error',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'content' => 'setContent',
        'stepId' => 'setStepId',
        'id' => 'setId',
        'name' => 'setName',
        'arguments' => 'setArguments',
        'state' => 'setState',
        'output' => 'setOutput',
        'approval' => 'setApproval',
        'toolCallId' => 'setToolCallId',
        'error' => 'setError',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'content' => 'getContent',
        'stepId' => 'getStepId',
        'id' => 'getId',
        'name' => 'getName',
        'arguments' => 'getArguments',
        'state' => 'getState',
        'output' => 'getOutput',
        'approval' => 'getApproval',
        'toolCallId' => 'getToolCallId',
        'error' => 'getError',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     */
    public function __construct(?array $data = null)
    {
        if (isset($data['type'])) {
            $this->container['type'] = $data['type'];
        }
        if (isset($data['content'])) {
            $this->container['content'] = $data['content'];
        }
        if (isset($data['stepId'])) {
            $this->container['stepId'] = $data['stepId'];
        }
        if (isset($data['id'])) {
            $this->container['id'] = $data['id'];
        }
        if (isset($data['name'])) {
            $this->container['name'] = $data['name'];
        }
        if (isset($data['arguments'])) {
            $this->container['arguments'] = $data['arguments'];
        }
        if (isset($data['state'])) {
            $this->container['state'] = $data['state'];
        }
        if (isset($data['output'])) {
            $this->container['output'] = $data['output'];
        }
        if (isset($data['approval'])) {
            $this->container['approval'] = $data['approval'];
        }
        if (isset($data['toolCallId'])) {
            $this->container['toolCallId'] = $data['toolCallId'];
        }
        if (isset($data['error'])) {
            $this->container['error'] = $data['error'];
        }
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function modelTypes()
    {
        return self::$modelTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function modelFormats()
    {
        return self::$modelFormats;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!isset($this->container['type']) || null === $this->container['type']) {
            $invalidProperties[] = "'type' can't be null";
        }
        if (!isset($this->container['content']) || null === $this->container['content']) {
            $invalidProperties[] = "'content' can't be null";
        }
        if (!isset($this->container['id']) || null === $this->container['id']) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (!isset($this->container['name']) || null === $this->container['name']) {
            $invalidProperties[] = "'name' can't be null";
        }
        if (!isset($this->container['arguments']) || null === $this->container['arguments']) {
            $invalidProperties[] = "'arguments' can't be null";
        }
        if (!isset($this->container['state']) || null === $this->container['state']) {
            $invalidProperties[] = "'state' can't be null";
        }
        if (!isset($this->container['toolCallId']) || null === $this->container['toolCallId']) {
            $invalidProperties[] = "'toolCallId' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'] ?? null;
    }

    /**
     * Sets type.
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets content.
     *
     * @return string
     */
    public function getContent()
    {
        return $this->container['content'] ?? null;
    }

    /**
     * Sets content.
     *
     * @param string $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets stepId.
     *
     * @return null|string
     */
    public function getStepId()
    {
        return $this->container['stepId'] ?? null;
    }

    /**
     * Sets stepId.
     *
     * @param null|string $stepId stepId
     *
     * @return self
     */
    public function setStepId($stepId)
    {
        $this->container['stepId'] = $stepId;

        return $this;
    }

    /**
     * Gets id.
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'] ?? null;
    }

    /**
     * Sets id.
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'] ?? null;
    }

    /**
     * Sets name.
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets arguments.
     *
     * @return string
     */
    public function getArguments()
    {
        return $this->container['arguments'] ?? null;
    }

    /**
     * Sets arguments.
     *
     * @param string $arguments arguments
     *
     * @return self
     */
    public function setArguments($arguments)
    {
        $this->container['arguments'] = $arguments;

        return $this;
    }

    /**
     * Gets state.
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'] ?? null;
    }

    /**
     * Sets state.
     *
     * @param string $state state
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets output.
     *
     * @return null|array<string,mixed>
     */
    public function getOutput()
    {
        return $this->container['output'] ?? null;
    }

    /**
     * Sets output.
     *
     * @param null|array<string,mixed> $output output
     *
     * @return self
     */
    public function setOutput($output)
    {
        $this->container['output'] = $output;

        return $this;
    }

    /**
     * Gets approval.
     *
     * @return null|ToolApprovalAGUI
     */
    public function getApproval()
    {
        return $this->container['approval'] ?? null;
    }

    /**
     * Sets approval.
     *
     * @param null|ToolApprovalAGUI $approval approval
     *
     * @return self
     */
    public function setApproval($approval)
    {
        $this->container['approval'] = $approval;

        return $this;
    }

    /**
     * Gets toolCallId.
     *
     * @return string
     */
    public function getToolCallId()
    {
        return $this->container['toolCallId'] ?? null;
    }

    /**
     * Sets toolCallId.
     *
     * @param string $toolCallId toolCallId
     *
     * @return self
     */
    public function setToolCallId($toolCallId)
    {
        $this->container['toolCallId'] = $toolCallId;

        return $this;
    }

    /**
     * Gets error.
     *
     * @return null|string
     */
    public function getError()
    {
        return $this->container['error'] ?? null;
    }

    /**
     * Sets error.
     *
     * @param null|string $error error
     *
     * @return self
     */
    public function setError($error)
    {
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }
}
