<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace Algolia\AlgoliaSearch\Model\AgentStudio;

/**
 * StatusEnum Class Doc Comment.
 *
 * @category Class
 */
class StatusEnum
{
    /**
     * Possible values of this enum.
     */
    public const RESOLVED = 'resolved';

    public const CANCELLED = 'cancelled';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RESOLVED,
            self::CANCELLED,
        ];
    }
}
