<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace Algolia\AlgoliaSearch\Model\AgentStudio;

use Algolia\AlgoliaSearch\Model\AbstractModel;
use Algolia\AlgoliaSearch\Model\ModelInterface;

/**
 * ToolResultPart Class Doc Comment.
 *
 * @category Class
 */
class ToolResultPart extends AbstractModel implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $modelTypes = [
        'type' => 'string',
        'toolCallId' => 'string',
        'toolName' => 'string',
        'output' => '\Algolia\AlgoliaSearch\Model\AgentStudio\ToolResultOutput',
        'providerOptions' => 'array<string,mixed>',
        'mcpConfigId' => 'string',
        'mcpConfigName' => 'string',
        'isTerminal' => 'bool',
        'outputMetadata' => 'array<string,mixed>',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $modelFormats = [
        'type' => null,
        'toolCallId' => null,
        'toolName' => null,
        'output' => null,
        'providerOptions' => null,
        'mcpConfigId' => null,
        'mcpConfigName' => null,
        'isTerminal' => null,
        'outputMetadata' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'toolCallId' => 'toolCallId',
        'toolName' => 'toolName',
        'output' => 'output',
        'providerOptions' => 'providerOptions',
        'mcpConfigId' => 'mcpConfigId',
        'mcpConfigName' => 'mcpConfigName',
        'isTerminal' => 'isTerminal',
        'outputMetadata' => 'outputMetadata',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'toolCallId' => 'setToolCallId',
        'toolName' => 'setToolName',
        'output' => 'setOutput',
        'providerOptions' => 'setProviderOptions',
        'mcpConfigId' => 'setMcpConfigId',
        'mcpConfigName' => 'setMcpConfigName',
        'isTerminal' => 'setIsTerminal',
        'outputMetadata' => 'setOutputMetadata',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'toolCallId' => 'getToolCallId',
        'toolName' => 'getToolName',
        'output' => 'getOutput',
        'providerOptions' => 'getProviderOptions',
        'mcpConfigId' => 'getMcpConfigId',
        'mcpConfigName' => 'getMcpConfigName',
        'isTerminal' => 'getIsTerminal',
        'outputMetadata' => 'getOutputMetadata',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     */
    public function __construct(?array $data = null)
    {
        if (isset($data['type'])) {
            $this->container['type'] = $data['type'];
        }
        if (isset($data['toolCallId'])) {
            $this->container['toolCallId'] = $data['toolCallId'];
        }
        if (isset($data['toolName'])) {
            $this->container['toolName'] = $data['toolName'];
        }
        if (isset($data['output'])) {
            $this->container['output'] = $data['output'];
        }
        if (isset($data['providerOptions'])) {
            $this->container['providerOptions'] = $data['providerOptions'];
        }
        if (isset($data['mcpConfigId'])) {
            $this->container['mcpConfigId'] = $data['mcpConfigId'];
        }
        if (isset($data['mcpConfigName'])) {
            $this->container['mcpConfigName'] = $data['mcpConfigName'];
        }
        if (isset($data['isTerminal'])) {
            $this->container['isTerminal'] = $data['isTerminal'];
        }
        if (isset($data['outputMetadata'])) {
            $this->container['outputMetadata'] = $data['outputMetadata'];
        }
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function modelTypes()
    {
        return self::$modelTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function modelFormats()
    {
        return self::$modelFormats;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!isset($this->container['type']) || null === $this->container['type']) {
            $invalidProperties[] = "'type' can't be null";
        }
        if (!isset($this->container['toolCallId']) || null === $this->container['toolCallId']) {
            $invalidProperties[] = "'toolCallId' can't be null";
        }
        if (!isset($this->container['toolName']) || null === $this->container['toolName']) {
            $invalidProperties[] = "'toolName' can't be null";
        }
        if (!isset($this->container['output']) || null === $this->container['output']) {
            $invalidProperties[] = "'output' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'] ?? null;
    }

    /**
     * Sets type.
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets toolCallId.
     *
     * @return string
     */
    public function getToolCallId()
    {
        return $this->container['toolCallId'] ?? null;
    }

    /**
     * Sets toolCallId.
     *
     * @param string $toolCallId toolCallId
     *
     * @return self
     */
    public function setToolCallId($toolCallId)
    {
        $this->container['toolCallId'] = $toolCallId;

        return $this;
    }

    /**
     * Gets toolName.
     *
     * @return string
     */
    public function getToolName()
    {
        return $this->container['toolName'] ?? null;
    }

    /**
     * Sets toolName.
     *
     * @param string $toolName toolName
     *
     * @return self
     */
    public function setToolName($toolName)
    {
        $this->container['toolName'] = $toolName;

        return $this;
    }

    /**
     * Gets output.
     *
     * @return ToolResultOutput
     */
    public function getOutput()
    {
        return $this->container['output'] ?? null;
    }

    /**
     * Sets output.
     *
     * @param ToolResultOutput $output output
     *
     * @return self
     */
    public function setOutput($output)
    {
        $this->container['output'] = $output;

        return $this;
    }

    /**
     * Gets providerOptions.
     *
     * @return null|array<string,mixed>
     */
    public function getProviderOptions()
    {
        return $this->container['providerOptions'] ?? null;
    }

    /**
     * Sets providerOptions.
     *
     * @param null|array<string,mixed> $providerOptions providerOptions
     *
     * @return self
     */
    public function setProviderOptions($providerOptions)
    {
        $this->container['providerOptions'] = $providerOptions;

        return $this;
    }

    /**
     * Gets mcpConfigId.
     *
     * @return null|string
     */
    public function getMcpConfigId()
    {
        return $this->container['mcpConfigId'] ?? null;
    }

    /**
     * Sets mcpConfigId.
     *
     * @param null|string $mcpConfigId mcpConfigId
     *
     * @return self
     */
    public function setMcpConfigId($mcpConfigId)
    {
        $this->container['mcpConfigId'] = $mcpConfigId;

        return $this;
    }

    /**
     * Gets mcpConfigName.
     *
     * @return null|string
     */
    public function getMcpConfigName()
    {
        return $this->container['mcpConfigName'] ?? null;
    }

    /**
     * Sets mcpConfigName.
     *
     * @param null|string $mcpConfigName mcpConfigName
     *
     * @return self
     */
    public function setMcpConfigName($mcpConfigName)
    {
        $this->container['mcpConfigName'] = $mcpConfigName;

        return $this;
    }

    /**
     * Gets isTerminal.
     *
     * @return null|bool
     */
    public function getIsTerminal()
    {
        return $this->container['isTerminal'] ?? null;
    }

    /**
     * Sets isTerminal.
     *
     * @param null|bool $isTerminal isTerminal
     *
     * @return self
     */
    public function setIsTerminal($isTerminal)
    {
        $this->container['isTerminal'] = $isTerminal;

        return $this;
    }

    /**
     * Gets outputMetadata.
     *
     * @return null|array<string,mixed>
     */
    public function getOutputMetadata()
    {
        return $this->container['outputMetadata'] ?? null;
    }

    /**
     * Sets outputMetadata.
     *
     * @param null|array<string,mixed> $outputMetadata outputMetadata
     *
     * @return self
     */
    public function setOutputMetadata($outputMetadata)
    {
        $this->container['outputMetadata'] = $outputMetadata;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }
}
