<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace Algolia\AlgoliaSearch\Model\AbtestingV3;

/**
 * EvidenceStatus Class Doc Comment.
 *
 * @category Class
 *
 * @description Whether this variant metric's result is trustworthy yet. This doesn't mean the A/B test has ended, and it doesn't declare a winning variant.  - `enough`. Enough evidence has accumulated to trust this metric's result for this variant. - `not_enough`. Evidence was computed but hasn't reached the threshold yet. - `collecting`. Evidence is still accumulating, so it's too early to report a verdict. - `no_data`. No usable data for this variant metric, and none is expected for it. - `unavailable`. Evidence can't be computed for this variant metric's comparison.
 */
class EvidenceStatus
{
    /**
     * Possible values of this enum.
     */
    public const ENOUGH = 'enough';

    public const NOT_ENOUGH = 'not_enough';

    public const COLLECTING = 'collecting';

    public const NO_DATA = 'no_data';

    public const UNAVAILABLE = 'unavailable';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ENOUGH,
            self::NOT_ENOUGH,
            self::COLLECTING,
            self::NO_DATA,
            self::UNAVAILABLE,
        ];
    }
}
