<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace Algolia\AlgoliaSearch\Model\AbtestingV3;

/**
 * MetricName Class Doc Comment.
 *
 * @category Class
 */
class MetricName
{
    /**
     * Possible values of this enum.
     */
    public const SEARCH_COUNT = 'search_count';

    public const TRACKED_SEARCH_COUNT = 'tracked_search_count';

    public const USER_COUNT = 'user_count';

    public const TRACKED_USER_COUNT = 'tracked_user_count';

    public const NO_RESULT_COUNT = 'no_result_count';

    public const ADD_TO_CART_COUNT = 'add_to_cart_count';

    public const PURCHASE_COUNT = 'purchase_count';

    public const CLICKED_SEARCH_COUNT = 'clicked_search_count';

    public const CONVERTED_SEARCH_COUNT = 'converted_search_count';

    public const CLICK_THROUGH_RATE = 'click_through_rate';

    public const CONVERSION_RATE = 'conversion_rate';

    public const ADD_TO_CART_RATE = 'add_to_cart_rate';

    public const PURCHASE_RATE = 'purchase_rate';

    public const AVERAGE_CLICK_POSITION = 'average_click_position';

    public const REVENUE = 'revenue';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SEARCH_COUNT,
            self::TRACKED_SEARCH_COUNT,
            self::USER_COUNT,
            self::TRACKED_USER_COUNT,
            self::NO_RESULT_COUNT,
            self::ADD_TO_CART_COUNT,
            self::PURCHASE_COUNT,
            self::CLICKED_SEARCH_COUNT,
            self::CONVERTED_SEARCH_COUNT,
            self::CLICK_THROUGH_RATE,
            self::CONVERSION_RATE,
            self::ADD_TO_CART_RATE,
            self::PURCHASE_RATE,
            self::AVERAGE_CLICK_POSITION,
            self::REVENUE,
        ];
    }
}
